### ISSUE TITLE
[Overlap in 3D Model - Text - And Scroll Icon]

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [carrycooldude/carrycooldude.github.io#6]
**Describe the bug**
The 3D Model hides the text behind it and the scroll icon is over the 3D Model.

**To Reproduce**
Visit the Website 

**Expected behavior**
Text - Model - And Icon all separated so that they are clearly distinguishable.

**Screenshots**
![image](https://user-images.githubusercontent.com/70568620/225849711-fa4cb1ab-8364-4b7a-bde2-c5d9a0171bf4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by carrycooldude** [comment]
Thanks @Prathamesh-Shanbhag for the feedback
Will do this asap ✨

**Comment by carrycooldude** [comment]
> **Describe the bug** The 3D Model hides the text behind it and the scroll icon is over the 3D Model.
> 
> **To Reproduce** Visit the Website
> 
> **Expected behavior** Text - Model - And Icon all separated so that they are clearly distinguishable.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/70568620/225849711-fa4cb1ab-8364-4b7a-bde2-c5d9a0171bf4.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10
![Screenshot from 2023-03-16 21-18-22](https://user-images.githubusercontent.com/41143496/225958412-14fb1085-a688-481d-96c4-b454704f53c0.png)
It's seems okay from my side...
> * Browser Chrome
